name: Jennifer Silver | Private tutor
markdown: redcarpet
highlighter: pygments
permalink: /articles/:title/
url: http://jensilver.co.uk
include: ['_pages']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]